export const ERR_NOT_FOUND = "ERR_NOT_FOUND";
export const UNEXPECTED_CODEC = "UNEXPECTED_CODEC";
export const UNEXPECTED_BUCKET_FORMAT = "UNEXPECTED_BUCKET_FORMAT";
export const UNEXPECTED_BUCKET_HASH = "UNEXPECTED_BUCKET_HASH";
export const UNEXPECTED_BUCKET_LEVEL = "UNEXPECTED_BUCKET_LEVEL";
export const UNEXPECTED_HASHER = "UNEXPECTED_HASHER";
export const UNEXPECTED_NODE_FORMAT = "UNEXPECTED_NODE_FORMAT";
export const UNEXPECTED_PREFIX_FORMAT = "UNEXPECTED_PREFIX_FORMAT";
