#!/bin/bash

# Allows git commit --amend to be used to edit commit message.
# Does not allow empty commits that are empty as a result of prettier --write.

# 1. Record exit code of git diff --cached --quiet to variable
if git diff --cached --quiet; then
    exit_code_before=0
else
    exit_code_before=1
fi

# 2. Run Prettier on staged files and update index
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again

# 3. Record another exit code of git diff --cached --quiet to new variable
if git diff --cached --quiet; then
    exit_code_after=0
else
    exit_code_after=1
fi

# 4. Exit with code 1 if exit codes do not match, else exit with code 0
if [ $exit_code_before -ne $exit_code_after ]; then
    exit 1
else
    exit 0
fi
